[package]
name = "ocaml"
version = "0.19.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
readme = "README.md"
keywords = ["ocaml", "rust", "ffi"]
repository = "https://github.com/zshipko/ocaml-rs"
license = "ISC"
description = "OCaml bindings for Rust"
documentation = "https://docs.rs/ocaml"
edition = "2018"

[package.metadata.docs.rs]
features = [ "without-ocamlopt", "derive", "link" ]

[dependencies]
ocaml-sys = {path = "./sys", version = "0.19.0"}
ocaml-derive = {path = "./derive", optional = true, version = "0.19"}
ocaml-interop = {git = "https://github.com/simplestaking/ocaml-interop", branch="runtime-handle"}
cstr_core = {version = "0.2", optional = true}
ndarray = {version = "^0.13.1", optional = true}

[features]
default = ["derive"]
derive = ["ocaml-derive"]
link = ["ocaml-sys/link"]
without-ocamlopt = ["ocaml-sys/without-ocamlopt"]
caml-state = ["ocaml-sys/caml-state"]
no-std = ["cstr_core/alloc"]
bigarray-ext = ["ndarray"]

[workspace]
members = [
  "derive",
  "sys",
  "test"
]
