[package]
name = "ocaml-sys"
version = "0.14.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
keywords = ["ocaml", "rust", "ffi"]
repository = "https://github.com/zshipko/ocaml-rs"
license = "ISC"
description = "Low-level OCaml bindings for Rust"
documentation = "https://docs.rs/ocaml-sys"
edition = "2018"

[dependencies]
cty = "0.2"

[build-dependencies]
cc = "1"
bindgen = "0.54"

[package.metadata.docs.rs]
features = [ "docs-rs" ]

[features]
link = []
docs-rs = []

